import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("company_sales_data.csv")
face_cream=df['facecream'].tolist()
face_wash=df['facewash'].tolist()
tooth_paste=df['toothpaste'].tolist()
m=df['moisturizer'].tolist()
soap=df['bathingsoap'].tolist()
sham=df['shampoo'].tolist()
plt.plot(face_cream,label="facecream sales data",marker='o',linewidth=3)
plt.plot(face_wash,label="facewash sales data",marker='o',linewidth=3)
plt.plot(tooth_paste,label="toothpaste sales data",marker='o',linewidth=3)
plt.plot(soap,label="bathingsoap sales data",marker='o',linewidth=3)
plt.plot(sham,label="shampoo sales data",marker='o',linewidth=3)
plt.plot(m,label="moisturizer sales data",marker='o',linewidth=3)
plt.title("Sales data")
plt.xlabel("Month number")
plt.ylabel("Sales units in number")
plt.legend()
plt.show()